#! /bin/bash

# Set the port number.
set port = 4000
if [ "$1" != "" ]; then
	 set port="$1"
fi

#nohup

while [ 1 ]; do
    # get rid of shutdown.txt
    if [ -e ../files/shutdown.txt ]; then
        rm -f ../files/shutdown.txt
        exit 0
    fi

    # archive any logs
    gzip ../log/*.log

    # create a new log and symlink to it
    logfile="../log/`date +"%b_%d___%H.%M"`.log"

    # Run.
    ./vw $port > $logfile 2>&1

    # give old connections a chance to die.
    sleep 100
done
