#! /bin/bash

# Set the port number.
set port = 4000
if [ "$1" != "" ]; then
	 set port="$1"
fi

set control = ""
if [ "$3" != "" ]; then
	set control="$3"
fi

#nohup

while [ 1 ]; do
    # get rid of shutdown.txt
    if [ -e shutdown.txt ]; then
        rm -f shutdown.txt
        exit 0
    fi

    # create a new log and symlink to it
    set logfile="../log/mylog.log"
    ln -fs $logfile ../log/current

    # Run.
    vw $port $control > $logfile 2>&1 &

    # archive any logs
    gzip ../log/*.log

    # give old connections a chance to die.
    sleep 100
done
